### ISSUE TITLE
NumberValue impls, comparing wrong value?

### ISSUE THREAD

**Issue by scott4moore** [ar90n/msgpack11#1]
Hi,

I was looking over your code and noticed that all the NumberValue implementations are all comparing to float64_value().  Is this what you meant to do?  I would assume for UINT32 you would want to call "other->uint32_value()" as an example.

class MsgPackUint32 final : public NumberValue<MsgPack::UINT32, uint32_t> {
    bool equals(const MsgPackValue * other) const override { return m_value == other->float64_value(); }
    bool less(const MsgPackValue * other)   const override { return m_value <  other->float64_value(); }

**Comment by ar90n** [comment]
Thanks for your comment.
Sorry for my late reply.I didn't notice your comment.

In the case of comparing two MsgPackValues, they cannot recognize the data type of another staticly.So, even if we called "other->uint32_value()",  other may not be uint32.
I wanted to solve this problem by casting it's value to double and then comparing them.
Because double has ability to express wide range value and I thought there was not losing data.

But I investigated this implementation again and found that there is a defect.
In the case of int64 or uint64, it didn't work correctly.
Because the value range of int64 and uint64 cannot be expresed  by double.
I already fixed this defect at v0.0.6.
