### ISSUE TITLE
Sending complex objects over the network and deserializing them

### ISSUE THREAD

**Issue by JoaoAJMatos** [ar90n/msgpack11#14]
I'm currently using this implementation of MessagePack for serializing/deserializing somewhat complex structures in a project I've been developing. 

I want to be able to send and receive serialized MessagePack Objects that can then be parsed and constructed in order to build the "complex structure" on the receiving end.

The complex structure in question is a Blockchain. My Blockchain class consists of an [array of Blocks](https://github.com/JoaoAJMatos/Dynamo-dev/blob/f89fa70bd811395c9ea64e18b7c04352c85a2ffa/src/dynamo/blockchain/Blockchain.h#L17) (Block class instances) which themselves contain an [array of Transactions](https://github.com/JoaoAJMatos/Dynamo-dev/blob/f89fa70bd811395c9ea64e18b7c04352c85a2ffa/src/dynamo/block/Block.h#L41) (Transaction class instances). 

I was able to serialize the Blockchain class by implementing  serialize methods in each of the classes: [Blockchain::serialize()](https://github.com/JoaoAJMatos/Dynamo-dev/blob/f89fa70bd811395c9ea64e18b7c04352c85a2ffa/src/dynamo/blockchain/Blockchain.cpp#L81), [Block::serialize()](https://github.com/JoaoAJMatos/Dynamo-dev/blob/f89fa70bd811395c9ea64e18b7c04352c85a2ffa/src/dynamo/block/Block.cpp#L216), [Transaction::serialize()](https://github.com/JoaoAJMatos/Dynamo-dev/blob/f89fa70bd811395c9ea64e18b7c04352c85a2ffa/src/dynamo/wallet/transaction/Transaction.cpp#L206).

After serializing the Blockchain, I would send the dump() output of that object to the receiving end, in order for it to [construct it's own Blockchain from the incoming packet](https://github.com/JoaoAJMatos/Dynamo-dev/blob/f89fa70bd811395c9ea64e18b7c04352c85a2ffa/src/dynamo/blockchain/Blockchain.cpp#L9). 

The problem is that, after serializing the Blockchain, I can access it's elements on the Sender Node (the one where the serialized blockchain originated from); however, I cannot to this on the Receiver Node. I get the MessagePack dump string but I am not able to parse the incoming buffer. I've checked the [parse error](https://github.com/ar90n/msgpack11/blob/74f638f404e9da8d33b30c26e8e5a9588a9b93d6/msgpack11.hpp#L194)  and it's populated with the message "end of buffer".

I'm not sure if this problem has to do with the way I try to serialize and construct the classes, or if it has to do with how I send the MessagePack dump() output to the receiver Node.

This issue might not have been very explicit but I am not sure how I can explain it better. I'm just looking for help to figure out what's causing this. I can get into further detail if someone's interested in helping out.

Also, keep in mind that I am a young dev, and I'm quite new to C++. The code may look like crap, be advised.

**Comment by ar90n** [comment]
Hi @JoaoAJMatos 
Thanks for your kind sample codes and information. I think that this trouble is caused by mishandling received data.
My guess is the following.

As you know, MessagePack is a binary serialization format. This 'binary' means that its serialized data contains null characters whose value is '\0'. So we cannot handle these values as a C language string that ends with a null character.

But [this line](https://github.com/JoaoAJMatos/Dynamo-dev/blob/e925ba7a8dd67515f330f787013bf74e9787ee97/src/dynamo/network/node/common/NodeClient.cpp#L68) constructs std::string instance from C language string. So if `response_buffer` contains null characters in the middle of itself, the constructor of std::string will stop reading the contents of `response_buffer` and construct an instance whose value is incompleted. I think this problem will be solved by adding the length of the content to the constructor of std::string.

The following code is a simulation to reproduce the above situation.  To mimic network communication, this code converts serizelizedCompany into a C language string and then creates a std::string instance.

```cpp
int main()
{
    using namespace msgpack11;
    std::string err;

    Person person1("John", 30);
    Person person2("Rita", 0);
    Person person3("Pedro", 34);

    Company myCompany({person1, person2, person3});

    std::string serializedCompany = myCompany.serialize().dump();
    std::cout << "Serialized company: " << serializedCompany << std::endl;

    const char* recvData = serializedCompany.c_str();
    const int  recvDataLength = serializedCompany.length();

    std::string recvSerializedCompany(recvData);  // this line doesn't work
    //std::string recvSerializedCompany(recvData, recvDataLength); // this line works
    std::cout << "Received Serialized company: " << recvSerializedCompany << std::endl;

    Company myNewCompany(recvSerializedCompany);
    myNewCompany.printEmployees();

    return 0;
}
```

The result of the above code is the following. We can see that deserialization fails.

```
$ ./a.out
Serialized company: employeesagenameJohnagenameRitaage"namePedro
Received Serialized company: employeesagenameJohnage
```

After switching the construction of recvSerializedCompany, we get the following result. It works correctly.

```
$ ./a.out
Serialized company: employeesagenameJohnagenameRitaage"namePedro
Received Serialized company: employeesagenameJohnagenameRitaage"namePedro
John 30
Rita 0
Pedro 34
```

I'm happy that this will be useful for you.

**Comment by JoaoAJMatos** [comment]
Thank you once more for the reply. 
You are completely right, I totally missed that! 
I will try your fix and edit this reply if it works.

I cannot thank you enough for your time and effort :) 

(Btw most of the code you see there is for debugging purposes and to try to find a work-around. Everything will be clean in the final project)

**Comment by JoaoAJMatos** [comment]
I have been testing out some stuff, and I realized something. 
How can I send the serialized data through the socket, if I can't get the full string with c_str()? 
Everything works as expected on the receiving end, the only problem is that I cannot send the full buffer to the client. 

Do you have any idea of how I could solve this?
